version: '3.5'
services:
  ros-bridge-moveit-setup:
    image: tetov/ros-abb-planner:19.11
    container_name: ros-bridge
    environment:
      - "ROS_HOSTNAME=ros-bridge"
      - "ROS_MASTER_URI=http://ros-master:11311"
    ports:
      - "9092:9090"
    command:
      - roslaunch
      - --wait
      - rosbridge_server
      - rosbridge_websocket.launch

  ros-fileserver:
    image: tetov/ros-abb-planner:19.11
    container_name: ros-fileserver
    environment:
      - ROS_HOSTNAME=ros-fileserver
      - ROS_MASTER_URI=http://ros-master:11311
    command:
      - roslaunch
      - --wait
      - file_server
      - file_server.launch

  # gui:
    # image: gramaziokohler/novnc:19.05
    # ports:
      # - "8080:8080"

  abb-tf-base_link:
    image: tetov/ros-abb-planner:19.11
    container_name: abb-tf-base_link
    environment:
      - ROS_HOSTNAME=abb-tf-base_link
      - ROS_MASTER_URI=http://ros-master:11311
    command:
      - rosrun
      - tf
      - static_transform_publisher
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '0'
      - '1'
      - world
      - base_link
      - '100'

  abb-description:
    image: tetov/ros-abb-planner:19.11
    container_name: abb-description
    environment:
      - ROS_HOSTNAME=abb-description
      - ROS_MASTER_URI=http://ros-master:11311
    command:
      - roslaunch
      - --wait


networks:
    default:
        name: ros-net
