version: '3.5'
services:
  abb-planner:
    environment:
      - DISPLAY=host.docker.internal:0.0
    command:
      - roslaunch
      - --wait
      - moveit_setup_assistant
      - setup_assistant.launch
    volumes:
        - ./volume:/volume
