version: "2.2"
services:
  ursim:
    image: arranhs/dockursim:latest
    environment:
      - ROBOT_MODEL=UR5
    ports:
      - 8080:8080
      - 29999:29999
      - 30001-30004:30001-30004
    volumes:
      - ./volume:/ursim
    privileged: true
    cpus: 1
